language: generic
before_script:
  - npm install -g markdownlint-cli
script:
  - /usr/local/bin/markdownlint content/*.md
  - /usr/local/bin/markdownlint content/blog/*.md
  - /usr/local/bin/markdownlint content/sammelsurium/*.md
