env:
  - hugo_version=0.80.0

jobs:
  include:
    - language: go
      stage: test
      go: 1.11
      install:
        - wget https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.tar.gz -O hugo.tar.gz
        - tar xvfz hugo.tar.gz
        - ./hugo version
      script:
        - ./hugo
    - language: go
      stage: deploy
      install:
      go: '1.11'
      install:
        - wget https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.tar.gz -O hugo.tar.gz
        - tar xvfz hugo.tar.gz
        - ./hugo version
        - echo $KNOWN_HOSTS_KEY >> $HOME/.ssh/known_hosts
      script:
        - ./hugo
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_a01276847ef6_key -iv $encrypted_a01276847ef6_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      deploy:
        - provider: script
          skip_cleanup: true
          script: rsync -avi --delete public/ $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER:public/
          on:
            branch: master
