language: go

go:
  - master

install:
  - go get github.com/gohugoio/hugo
  - npm install -g markdownlint-cli

script:
  - hugo
  - markdownlint content/*.md
  - markdownlint content/blog/*.md
  - markdownlint content/sammelsurium/*.md
