language: generic
before_script:
  - npm install -g markdownlint-cli
script:
  - /usr/local/binmarkdownlint content/*.md
  - /usr/local/binmarkdownlint content/blog/*.md
  - /usr/local/binmarkdownlint content/sammelsurium/*.md

