title: "noqqe.de"
baseurl:  "https://noqqe.de"
languageCode: "de-de"
theme: "noqqe"
path: "blog"
publishdir: "public"
metaDataFormat: "yaml"
disableKinds:
  - "taxonomyTerm"

params:
  Description: "No advertising, no support, no bug fixes, payment in advance. &mdash; AT&T Unix Policy (1984)"
  Copyright: "Content is licensed under a Creative Commons Attribution 4.0 International License"
  Author: "Florian Baumann"
  githubuser: "noqqe"
  Keywords: "OpenBSD, Administration, Code, Crypto, DevOps, Linux, OpenBSD, Sysadmin, SRE"
  Twitter: "noqqe"

taxonomies:
  tag: "tags"

permalinks:
  blog: "blog/:year/:month/:day/:filename/"
  photos: "photos/:year/:month/:day/:filename/"
  sammelsurium: "sammelsurium/:filename/"
