title: "noqqe.de"
baseurl:  "https://noqqe.de"
languageCode: "de-de"
theme: "noqqe-v3"
path: "blog"
paginate: 3
paginatePath: "page"
publishdir: "public"
metaDataFormat: "yaml"

params:
  Description: "No advertising, no support, no bug fixes, payment in advance.<br/> &mdash; AT&T Unix Policy (1984)"
  Copyright: "Content is licensed under a Creative Commons Attribution 4.0 International License"
  Author: "Florian Baumann"
  githubuser: "noqqe"
  Keywords: "OpenBSD, Administration, bash, BSD, Code, Crypto, DevOps, Linux, Debian, Ubuntu, Mail, Statistik"
  Twitter: "@noqqe"

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  post: "blog/:year/:month/:day/:filename/"

menu:
  main:
  - name: "Projects"
    weight: 50
    identifier: "Projects"
    url: "/Projects/"
  - name: "Archives"
    weight: 70
    identifier: "Archives"
    url: "/archives/"
  - name: "Books"
    weight: 90
    identifier: "Books"
    url: "/books/"
  - name: "PGP"
    weight: 110
    identifier: "PGP"
    url: "/pgp/"
