baseurl = "http://localhost:1313"
languageCode = "en-us"
title = "noqqe.de"
publishdir = "public"
paginate = 10
paginatePath = "page"

[permalinks]
  post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "About"
    weight = -110
    identifier = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = -120
    identifier = "Projects"
    url = "/Projects/"
[[menu.main]]
    name = "Archives"
    weight = -130
    identifier = "Archives"
    url = "/archives/"
[[menu.main]]
    name = "Impressum"
    weight = -100
    identifier = "Impressum"
    url = "/impressum/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  Description = "No advertising, no support, no bug fixes, payment inadvance."
  author = "Florian Baumann"
  githubuser = "noqqe"

