title: "noqqe.de"
baseurl:  "https://noqqe.de"
languageCode: "de-de"
theme: "noqqe"
path: "blog"
publishdir: "public"
metaDataFormat: "yaml"

params:
  Description: "No advertising, no support, no bug fixes, payment in advance.<br/> &mdash; AT&T Unix Policy (1984)"
  Copyright: "Content is licensed under a Creative Commons Attribution 4.0 International License"
  Author: "Florian Baumann"
  githubuser: "noqqe"
  Keywords: "OpenBSD, Administration, bash, BSD, Code, Crypto, DevOps, Linux, Debian, Ubuntu, Mail, Statistik"
  Twitter: "noqqe"

taxonomies:
  tag: "tags"

permalinks:
  blog: "blog/:year/:month/:day/:filename/"
  sammelsurium: "sammelsurium/:filename/"
  links: "links/:filename/"

menu:
  main:
  - name: "blog"
    weight: 10
    url: "/blog/"
  - name: "projects"
    weight: 20
    url: "/projects/"
  - name: "pgp"
    weight: 30
    url: "/pgp/"
  - name: "books"
    weight: 40
    url: "/books/"
  - name: "about"
    weight: 40
    url: "/about/"
