title: "noqqe.de"
baseurl:  "https://noqqe.de"
languageCode: "de-de"
theme: "noqqe"
path: "blog"
paginate: 10
paginatePath: "page"
publishdir: "public"
metaDataFormat: "yaml"

params:
  Description: "No advertising, no support, no bug fixes, payment inadvance.<br/> &mdash; AT&T Unix Policy (1984)"
  Copyright: "&copy; 2015 Florian Baumann.<br/>CC BY-NC-SA Some rights reserved."
  Author: "Florian Baumann"
  githubuser: "noqqe"

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  post: "blog/:year/:month/:day/:filename/"

menu:
  main:
  - name: "Projects"
    weight: 50
    identifier: "Projects"
    url: "/Projects/"
  - name: "Archives"
    weight: 70
    identifier: "Archives"
    url: "/archives/"
  - name: "Books"
    weight: 90
    identifier: "Books"
    url: "/books/"
  - name: "Impressum"
    weight: 110
    identifier: "Impressum"
    url: "/impressum/"
